shop/urls.py
from django.urls import path
from shop.views import products_catalog, \
                       cart_add_one, \
                       cart_delete_one, \
                       cart_remove, \
                       product

app_name = 'products_catalog'

urlpatterns = [
    path('', products_catalog, name='index'),
    path('category/<int:category_id>/',
         products_catalog, name='category'),
    path('page/<int:page_number>/',
         products_catalog, name='paginator'),
    path('product/<int:software_id>',
         product, name='index'),
    path('cart/add/<int:software_id>/',
         cart_add_one, name='cart_add_one'),
    path('cart/delete/<int:software_id>/',
         cart_delete_one, name='cart_delete_one'),
    path('cart/remove/<int:cart_id>/',
         cart_remove, name='cart_remove'),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from shop.views import index, \
                       sitemap, \
                       about_us, \
                       product, \
                       cart, \
                       faq, \
                       search_product

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name='index'),
    path("sitemap", sitemap, name='sitemap'),
    path("about_us", about_us, name='about_us'),
    path("product", product, name='product'),
    path("cart", cart, name='cart'),
    path("faq", faq, name='faq'),
    path("search", search_product, name='search'),
    path("input_user/",
         include('users.urls',
                 namespace='users')),
    path("products_catalog/",
         include('shop.urls',
                 namespace='products_catalog')),
    path("product/",
         include('shop.urls',
                 namespace='product')),
    path("ckeditor5/",
         include('django_ckeditor_5.urls'),
         name="ck_editor_5_upload_file"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import login_user, \
                        register, \
                        my_account, \
                        exit_my_account, \
                        delete_profile, \
                        email_verification, \
                        forgot_password, \
                        create_new_password, \
                        delete_user_confirmation

app_name = 'users'

urlpatterns = [
    path("login/", login_user,
         name='login_user'),
    path("register/", register,
         name='register'),
    path("my_account/", my_account,
         name='my_account'),
    path("exit_my_account/", exit_my_account,
         name='exit_my_account'),
    path("delete_profile/", delete_profile,
         name='delete_profile'),
    path("verify/<str:email>/<uuid:code>/",
         email_verification,
         name='email_verification'),
    path("forgot_password/", forgot_password,
         name='forgot_password'),
    path("create_new_password/<str:email>/<uuid:code>/",
         create_new_password,
         name='create_new_password'),
    path("delete_user_confirmation/",
         delete_user_confirmation,
         name='delete_user_confirmation'),
    path("verify/<str:email>/<uuid:code>/",
         email_verification,
         name='email_verification'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.utils.timezone import now
from django.conf import settings
from django.urls import reverse
from django.db import models

email_confirmation_time_hours = \
    settings.EMAIL_CONFIRMATION_TIME_HOURS
password_recovery_time_hours = \
    settings.PASSWORD_RECOVERY_TIME_HOURS


class User(AbstractUser):
    image = models.ImageField(null=True, blank=True, upload_to='images_users')
    is_verified_email = models.BooleanField(default=False)
    email = models.EmailField(unique=True, blank=False)
    surname = models.CharField(max_length=150, blank=True)
    birthday = models.DateField(null=True, blank=False)
    gender = models.TextField(max_length=1, null=True, blank=False)
    phone = models.TextField(null=True, blank=False, unique=True)
    address = models.CharField(max_length=150, null=True, blank=False)

    def __str__(self):
        return f'Login: {self.username} ' \
               f'| Staff: {self.is_staff} ' \
               f'| Superuser: {self.is_superuser} '


class EmailVerification(models.Model):
    code = models.UUIDField(unique=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()

    def send_verification_email(self):
        half_link = reverse("users:email_verification",
                            kwargs={"email": self.user.email,
                                    "code": self.code})
        verification_link_email = f"{settings.DOMAIN_NAME}{half_link}"

        subject = \
            f"Подтверждение адреса электронной почты"
        message = \
            f"Для подтверждения адреса электронной " \
            f"почты в учетной записи: " \
            f"{self.user.first_name} {self.user.last_name} " \
            f"перейдите по ссылке: {verification_link_email} ." \
            f" Cсылка активна {email_confirmation_time_hours} " \
            f"часов с момента отправки данного письма."

        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email],
            fail_silently=False,
        )

    def is_expired(self):
        return True if now() >= self.expiration else False

    def __str__(self):
        return f"Chek email {self.user.email}"

    class Meta:
        verbose_name_plural = "Подтвержденные/активированные аккаунты"
        verbose_name = "подтвержденные/активированные аккаунты"


class PasswordRecovery(models.Model):
    code = models.UUIDField(unique=True)
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()
    link_used = models.BooleanField(default=False)

    def send_password_recovery_email(self):
        half_link = reverse("users:create_new_password",
                            kwargs={"email": self.user.username,
                                    "code": self.code})
        password_recovery_link = f"{settings.DOMAIN_NAME}{half_link}"

        subject = \
            "Восстановление пароля учетной записи"
        message = \
            f"Для смены пароля перейдите " \
            f"по ссылке: {password_recovery_link} ."\
            f" Cсылка активна " \
            f"{password_recovery_time_hours} " \
            f"часов c момента отправки данного письма."

        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email],
            fail_silently=False,
        )

    def is_expired(self):
        return True if now() >= self.expiration else False

    def __str__(self):
        return f"Password recovery {self.user.username}"

    class Meta:
        verbose_name_plural = "Восстановление/сменя пароля к аккаунту"
        verbose_name = "восстановление/сменя пароля к аккаунту"

users/views.py
from uuid import uuid4
from django.utils.timezone import now
from django.contrib.auth.decorators import login_required
from datetime import timedelta
from django.shortcuts import render, \
    HttpResponseRedirect
from django.contrib.auth import authenticate, \
    login, \
    logout
from django.urls import reverse
from django.contrib.messages import success, \
    error
from users.forms import UserLoginForm, \
    UserRegisterForm, \
    UserProfileForm, \
    UserRecoveryPasswordForm, \
    UserCreatNewPasswordForm
from users.models import User, \
    EmailVerification, \
    PasswordRecovery
from shop.views import title_for_basic_template, \
    data_for_basic_template
from django.conf import settings

QUANTITY_LIMIT_EMAIL_DAY: int = 5
email_confirmation_time_hours = \
    settings.EMAIL_CONFIRMATION_TIME_HOURS
password_recovery_time_hours = \
    settings.PASSWORD_RECOVERY_TIME_HOURS


def login_user(request):
    """
    Displays the login page for the personal account
    and processes the user authentication form.

    :return: Redirection to the user's personal account page
    in case of successful authentication.
    Otherwise, display the login page with the form.
    """
    title_login: str = 'Вход в личный кабинет - '

    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username,
                                password=password)
            if user:
                login(request, user)
                return HttpResponseRedirect(reverse('users:my_account'))
            else:
                message_error_for_user: str = ''
                if User.objects.filter(username=username).exists():
                    message_error_for_user = 'Неверный пароль'
                else:
                    message_error_for_user = 'Учетной записи с таким именем ' \
                                             'пользователя нет в базе данных'
                error(request, message_error_for_user)
    else:
        form = UserLoginForm(data=request.POST)

    context = {
        'form': form,
        'page_title': title_login + title_for_basic_template(),
    }
    return render(request, 'login.html', context)


def register(request):
    """
    Processes the form to create a new user account.
    Saves the user in the database by filling the username field with the data
    from the email field.

    :return: Redirecting to the login page in case of successful registration.
    Otherwise, displaying the registration page with the form
    """
    title_register: str = 'Регистрация покупателя - '

    if request.method == 'POST':
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            username_form = form.save(commit=False)
            username_form.username = form.cleaned_data['email']
            username_form.save()

            expiration = now() + timedelta(hours=
                                           settings.EMAIL_CONFIRMATION_TIME_HOURS)
            new_user = User.objects.get(username=
                                        username_form.username)
            confirmation_email = \
                EmailVerification.objects.create(user=new_user,
                                                 code=uuid4(),
                                                 expiration=expiration)
            confirmation_email.send_verification_email()
            message_success_for_user: str = \
                'Вы успешно прошли регистрацию!'
            success(request, message_success_for_user)
            return HttpResponseRedirect(reverse('users:login_user'))
    else:
        form = UserRegisterForm()

    context = {
        'form': form,
        'page_title': title_register + title_for_basic_template()
    }
    return render(request, 'register.html', context)


def email_verification(request, email, code):
    title_register: str = \
        'Подтверждение адреса электронной почты - '

    if User.objects.filter(email=email).exists():
        user = User.objects.get(email=email)
        for_email_verification = \
            EmailVerification.objects.filter(user=user,
                                             code=code)
        if for_email_verification.exists() and \
                not for_email_verification.first().is_expired():
            user.is_verified_email = True
            user.save()
            message_success_for_user: str = \
                f'Вы успешно подвердили ' \
                f'адрес электронной почты: ' \
                f'{email}'
            success(request, message_success_for_user)

        elif for_email_verification.exists() and \
                for_email_verification.first().is_expired():
            message_error_for_user: str = \
                f'Время длительностью в ' \
                f'{email_confirmation_time_hours} ' \
                f'часов отведенное на подтверждение ' \
                f'адреса электронной почты вышло.' \
                f'Обратитесь к администрации ' \
                f'ресурса .'
            error(request, message_error_for_user)

        elif not for_email_verification.exists():
            message_error_for_user = \
                f'Письмо с данной ссылкой некогда ' \
                f'не отправлялось ' \
                f'на электронную почту {email} .'
            error(request, message_error_for_user)
    else:
        message_error_for_user = 'Такого пользователя ' \
                                 'не существует.'
        error(request, message_error_for_user)

    context = {
        'page_title': title_register + title_for_basic_template()
    }
    return render(request, 'email_verification.html', context)


def forgot_password(request):
    title_register: str = 'Востановление пароля - '

    if request.method == 'POST':
        form = UserRecoveryPasswordForm(data=request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            user = User.objects.filter(email=email)

            if user.exists() and \
                    user.first().is_verified_email:

                end_date = now()
                start_date = end_date - timedelta(hours=24)
                count_emails = \
                    PasswordRecovery.objects.filter(user=user.first(),
                                                    created__range=
                                                    (start_date, end_date)).count()

                if count_emails <= QUANTITY_LIMIT_EMAIL_DAY:
                    expiration = now() + timedelta(hours=
                                                   password_recovery_time_hours)
                    for_password_recovery = \
                        PasswordRecovery.objects.create(code=uuid4(),
                                                        user=user.first(),
                                                        expiration=expiration)

                    for_password_recovery.send_password_recovery_email()

                    message_success_for_user: str = \
                        f"На электронную почту {email} " \
                        f"отправлено письмо содержащее " \
                        f"ссылку для востановления пароля."
                    success(request, message_success_for_user)
                else:
                    message_error_for_user: str = \
                        f"В сутки можно отправить " \
                        f"{QUANTITY_LIMIT_EMAIL_DAY} " \
                        f"писем. "
                    error(request, message_error_for_user)
            else:
                message_error_for_user: str = \
                    f"Учетной записи с таким адресом " \
                    f"электронной почты не существует " \
                    f"или электроная почта не подтверждена."
                error(request, message_error_for_user)
    else:
        form = UserRecoveryPasswordForm()

    context = {
        'form': form,
        'page_title': title_register + title_for_basic_template()
    }
    return render(request, 'forgot_password.html', context)


def create_new_password(request, email, code):
    title_register: str = \
        'Создание нового пароля взамен забытого - '

    if User.objects.filter(email=email).exists():
        user = User.objects.get(email=email)
        application_for_new_password = \
            PasswordRecovery.objects.filter(user=user,
                                            code=code)

        if application_for_new_password.exists() and \
                not application_for_new_password.first().is_expired() and \
                not application_for_new_password.first().link_used:

            if request.method == 'POST':
                form = UserCreatNewPasswordForm(data=request.POST)
                if form.is_valid():
                    new_password = form.cleaned_data['password2']
                    user.set_password(new_password)
                    user.save()

                    for_neutralize_link = \
                        application_for_new_password.first()
                    for_neutralize_link.link_used = True
                    for_neutralize_link.save()

                    message_success_for_user: str = \
                        "Ваш пароль был изминен !"
                    success(request, message_success_for_user)
                    return HttpResponseRedirect(reverse('users:login_user'))

        elif application_for_new_password.exists() and \
                not application_for_new_password.first().is_expired() and \
                application_for_new_password.first().link_used:

            message_error_for_user: str = \
                'Эта ссылка уже использована один раз.' \
                'Повторное использование невозможно .'
            error(request, message_error_for_user)

users/templates/delete_user_confirmation.html
{% extends 'base_entry.html' %}
{% load static %}


<!-- Libs CSS
============================================ -->
{% block libs_css %}
<link href="{% static 'css/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
{% endblock %}

<!-- Theme CSS
============================================ -->
{% block theme_css %}
<link href="{% static 'css/themecss/so_megamenu.css' %}" rel="stylesheet">
<link href="{% static 'css/footer1.css' %}" rel="stylesheet">
<link href="{% static 'css/header1.css' %}" rel="stylesheet">
<link href="{% static 'css/theme.css' %}" id="color_scheme" rel="stylesheet" >
{% endblock %}

{% block stile_body_two_line %}
    <body class="res layout-subpage">
        <div id="wrapper" class="wrapper-full ">
{% endblock %}

<!-- Main Container  -->
{% block main_container %}
    <div class="text-center" style="margin-top: 150px">
        <h1><b>Вы уверены, что хотите удалить аккаунт?</b></h1>
        <br>
        <h4 style="color: #DA2723">* восстановить аккаунт будет невозможно, вся история покупок
                                                 и программа лояльности будут потеряны навсегда </h4>
    </div>
    <br>
    <form action="{% url 'users:register' %}" method="post" novalidate style="margin-left: auto; margin-right: auto; width: 400px; ">
    {% csrf_token %}
        <div style="display: flex; justify-content: center; margin: 40px 0px 150px 0px">
            <a href="{% url 'users:my_account' %}" class="btn btn-md btn-primary" style="margin-right: 30px;" title="Назад">Назад</a>
            <input formaction="{% url 'users:delete_profile' %}" type="submit" value="Удалить аккаунт" class="btn btn-md btn-danger">
        </div>
    </form>
{% endblock %}
<!-- //Main Container -->

<!-- Include Libs & Plugins
============================================ -->
{% block libs_and_plugins %}
{% endblock %}

<!-- Theme files
============================================ -->
{% block theme_files %}
{% endblock %}

users/templates/email_verification.html
{% extends 'base_entry.html' %}
{% load static %}

<!-- Libs CSS
============================================ -->
{% block libs_css %}
<link rel="stylesheet" href="{% static 'css/bootstrap/css/bootstrap.min.css' %}">
<link href="{% static 'css/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
{% endblock %}

<!-- Theme CSS
============================================ -->
{% block theme_css %}
<link href="{% static 'css/footer1.css' %}" rel="stylesheet">
<link href="{% static 'css/header1.css' %}" rel="stylesheet">
<link href="{% static 'css/themecss/so_megamenu.css' %}" rel="stylesheet">
<link href="{% static 'css/theme.css' %}"  rel="stylesheet" id="color_scheme">
{% endblock %}

{% block stile_body_two_line %}
    <body class="res layout-subpage">
        <div id="wrapper" class="wrapper-full ">
{% endblock %}

<!-- Main Container  -->
{% block main_container %}
<div class="main-container container">
    <ul class="header-main">
        <li class="home"><a href="{% url 'index' %}">Главная</a><i class="fa fa-angle-right" aria-hidden="true"></i></li>
        <li>Подтверждение электронной почты</li>
    </ul>
    <div class="row">
        <br><br><br><br><br><br>
            <br><br><br><br><br><br>
                <div class="text-center">
                    <div class="alert">
                        {% if messages %}
                            {% for message in messages %}
                                {% if "error" in message.tags %}
                                    <div class="alert-danger">{{ message }}</div>
                                {% endif %}
                                {% if "success" in message.tags %}
                                    <div class="alert-success">{{ message }}</div>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            <br><br><br><br><br><br>
        <br><br><br><br><br><br>
    </div>
</div>
{% endblock %}
<!-- //Main Container -->

<!-- Include Libs & Plugins
============================================ -->
{% block libs_and_plugins %}
{% endblock %}

<!-- Theme files
============================================ -->
{% block theme_files %}
{% endblock %}

users/templates/forgot_password.html
{% extends 'base_entry.html' %}
{% load static %}

<!-- Libs CSS
============================================ -->
{% block libs_css %}
<link href="{% static 'css/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" >
<link href="{% static 'css/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
{% endblock %}

<!-- Theme CSS
============================================ -->
{% block theme_css %}
<link href="{% static 'css/footer1.css' %}" rel="stylesheet">
<link href="{% static 'css/header1.css' %}" rel="stylesheet">
<link href="{% static 'css/themecss/so_megamenu.css' %}" rel="stylesheet">
<link href="{% static 'css/theme.css' %}"  rel="stylesheet" id="color_scheme">
{% endblock %}

{% block stile_body_two_line %}
    <body class="res layout-subpage">
        <div id="wrapper" class="wrapper-full ">
{% endblock %}

<!-- Main Container  -->
{% block main_container %}
<div class="main-container container">
    <ul class="header-main">
        <li class="home"><a href="{% url 'index' %}">Главная</a><i class="fa fa-angle-right" aria-hidden="true"></i></li>
        <li>Забыли пароль</li>
    </ul>
    <div class="row">
        <div id="content" class="col-sm-12">
            <div class="page-login center-block">
                <div class="account-border ">
                <style> .indented {
                padding-bottom: 200px;
                padding-top: 200px;
                }
                </style>
                    <div class="row indented">
                        <form action="{% url 'users:forgot_password' %}" method="post">
                            <div class="login" style="margin-left: 330px;margin-right: 330px;">
                                <div class="well">
                                    <h2><i class="fa fa-file-text-o" aria-hidden="true"></i>Воcстановление пароля</h2>
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label class="control-label" for="{{ form.username.id_for_label }}">Адрес электронной почты:</label>
                                        <p>{{ form.email }}</p>
                                    </div>
                                    <div class="form-group">
                                        <div class="alert text-center">
                                            {% if messages %}
                                                {% for message in messages %}
                                                    {% if "error" in message.tags %}
                                                        <div class="alert-danger">{{ message }}</div>
                                                    {% endif %}
                                                    {% if "success" in message.tags %}
                                                        <div class="alert-success" >{{ message }}</div>
                                                    {% endif %}
                                                {% endfor %}
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                                <div class="bottom-form">
                                    <input type="submit" value="Оправить письмо" class="btn btn-default pull-right">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
<!-- //Main Container -->

<!-- Include Libs & Plugins
============================================ -->
{% block libs_and_plugins %}
{% endblock %}

<!-- Theme files
============================================ -->
{% block theme_files %}
{% endblock %}

users/templates/login.html
{% extends 'base_entry.html' %}
{% load static %}

<!-- Libs CSS
============================================ -->
{% block libs_css %}
<link href="{% static 'css/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" >
<link href="{% static 'css/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
{% endblock %}

<!-- Theme CSS
============================================ -->
{% block theme_css %}
<link href="{% static 'css/footer1.css' %}" rel="stylesheet">
<link href="{% static 'css/header1.css' %}" rel="stylesheet">
<link href="{% static 'css/themecss/so_megamenu.css' %}" rel="stylesheet">
<link href="{% static 'css/theme.css' %}"  rel="stylesheet" id="color_scheme">
{% endblock %}

{% block stile_body_two_line %}
    <body class="res layout-subpage">
        <div id="wrapper" class="wrapper-full ">
{% endblock %}

<!-- Main Container  -->
{% block main_container %}
<div class="main-container container">
    <ul class="header-main ">
        <li class="home"><a href="{% url 'index' %}">Главная</a><i class="fa fa-angle-right" aria-hidden="true"></i></li>
        <li>Войти</li>
    </ul>
    <br><br><br>
    <br><br><br>
    <br><br><br>
    <div class="row">
        <div id="content" class="col-sm-12">
            <div class="page-login">
                <div class="account-border">
                    <div class="row">
                        <div class="col-sm-6 new-customer">
                            <div class="well">
                                <h2><i class="fa fa-file-o" aria-hidden="true"></i>Новый клиент</h2>
                                <p>Создав учетную запись, вы сможете совершать покупки быстрее, быть в курсе статуса заказа и отслеживать ранее сделанные заказы.</p>
                            </div>
                            <div class="bottom-form">
                                <a href="{% url 'users:register' %}" class="btn btn-default pull-right">Регистрация</a>
                            </div>
                        </div>
                        <form action="{% url 'users:login_user' %}" method="post">
                            <div class="col-sm-6 customer-login">
                                <div class="well">
                                    <h2><i class="fa fa-file-text-o" aria-hidden="true"></i>Постоянный покупатель</h2>
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label class="control-label" for="{{ form.username.id_for_label }}">Адрес электронной почты:</label>
                                        <p>{{ form.username }}</p>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label" for="{{ form.password.id_for_label }}">Пароль:</label>
                                        <p>{{ form.password }}</p>
                                        <div class="alert text-center">
                                            {% if messages %}
                                                {% for message in messages %}
                                                    {% if "error" in message.tags %}
                                                        <div class="alert-danger">{{ message }}</div>
                                                    {% endif %}
                                                    {% if "success" in message.tags %}
                                                        <div class="alert-success" >{{ message }}</div>
                                                    {% endif %}
                                                {% endfor %}
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                                <div class="bottom-form">
                                    <a href="{% url 'users:forgot_password' %}" class="forgot">Забыли пароль ?</a>
                                    <input type="submit" value="Войти" class="btn btn-default pull-right">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
<br><br><br>
<br><br><br>
<br><br><br>
</div>
{% endblock %}
<!-- //Main Container -->

<!-- Include Libs & Plugins
============================================ -->
{% block libs_and_plugins %}
{% endblock %}

<!-- Theme files
============================================ -->
{% block theme_files %}
{% endblock %}