shop/urls.py
from django.urls import path
from shop.views import products_catalog, \
                       cart_add_one, \
                       cart_delete_one, \
                       cart_remove, \
                       product

app_name = 'products_catalog'

urlpatterns = [
    path('', products_catalog, name='index'),
    path('category/<int:category_id>/',
         products_catalog, name='category'),
    path('page/<int:page_number>/',
         products_catalog, name='paginator'),
    path('product/<int:software_id>',
         product, name='index'),
    path('cart/add/<int:software_id>/',
         cart_add_one, name='cart_add_one'),
    path('cart/delete/<int:software_id>/',
         cart_delete_one, name='cart_delete_one'),
    path('cart/remove/<int:cart_id>/',
         cart_remove, name='cart_remove'),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from shop.views import index, \
                       sitemap, \
                       about_us, \
                       product, \
                       cart, \
                       faq, \
                       search_product

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name='index'),
    path("sitemap", sitemap, name='sitemap'),
    path("about_us", about_us, name='about_us'),
    path("product", product, name='product'),
    path("cart", cart, name='cart'),
    path("faq", faq, name='faq'),
    path("search", search_product, name='search'),
    path("input_user/",
         include('users.urls',
                 namespace='users')),
    path("products_catalog/",
         include('shop.urls',
                 namespace='products_catalog')),
    path("product/",
         include('shop.urls',
                 namespace='product')),
    path("ckeditor5/",
         include('django_ckeditor_5.urls'),
         name="ck_editor_5_upload_file"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import login_user, \
                        register, \
                        my_account, \
                        exit_my_account, \
                        delete_profile, \
                        email_verification, \
                        forgot_password, \
                        create_new_password, \
                        delete_user_confirmation

app_name = 'users'

urlpatterns = [
    path("login/", login_user,
         name='login_user'),
    path("register/", register,
         name='register'),
    path("my_account/", my_account,
         name='my_account'),
    path("exit_my_account/", exit_my_account,
         name='exit_my_account'),
    path("delete_profile/", delete_profile,
         name='delete_profile'),
    path("verify/<str:email>/<uuid:code>/",
         email_verification,
         name='email_verification'),
    path("forgot_password/", forgot_password,
         name='forgot_password'),
    path("create_new_password/<str:email>/<uuid:code>/",
         create_new_password,
         name='create_new_password'),
    path("delete_user_confirmation/",
         delete_user_confirmation,
         name='delete_user_confirmation'),
    path("verify/<str:email>/<uuid:code>/",
         email_verification,
         name='email_verification'),
]

shop/forms.py
from django import forms
from django.db import models
from shop.models import UsersQuestions


class ShopFaqForm(forms.ModelForm):
    question_timestamp = models.DateTimeField(auto_now_add=True, null=True)
    userquestion = forms.CharField(label="Текст сообщения:",
        widget=forms.Textarea(
            attrs={'max_length': 500,
                   'class': 'form-control',
                   'id': 'input-comment',
                   'placeholder': 'Текст сообщения',
                   'rows': 10,
                   'name': 'comment'}))

    class Meta:
        model = UsersQuestions
        fields = ('userquestion', 'upload')

shop/views.py
from django.urls import reverse
from shop.forms import ShopFaqForm
from django.contrib.messages import error
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.search import SearchQuery, \
                                           SearchVector
from django.shortcuts import render, \
                             HttpResponseRedirect
from shop.models import ImageCollectionForIndex,\
                        FeaturesSoftware, \
                        SoftwareCategory, \
                        DevelopmentTeam, \
                        Software, \
                        Cart, \
                        FAQ

NUMBER_ITEM_PER_CATALOG_PAGE: int = 6


def title_for_basic_template():
    text: str = 'Дипломная работа'
    return text


def data_for_basic_template(request):
    cart_user = None

    if not request.user.is_anonymous:
        cart_user = Cart.objects.filter(user=request.user)

    data = {
        "software_category": SoftwareCategory.objects.all(),
        "cart": cart_user
    }
    return data


def index(request):
    title_index = 'Главная страница - '

    if ImageCollectionForIndex.objects.all().exists():
        all_image = \
            ImageCollectionForIndex.objects.all()
    else:
        all_image = None

    context = {
        "all_image": all_image,
        "page_title": title_index + title_for_basic_template()
    }
    return render(request, 'index.html',
                  {**context, **data_for_basic_template(request)})


def sitemap(request):
    title_sitemap = 'Карта сайта - '

    context = {
        'page_title': title_sitemap + title_for_basic_template()
    }
    return render(request, 'sitemap.html',
                  {**context, **data_for_basic_template(request)})


def about_us(request):
    title_about_us = 'О нас / Наши контакты - '

    context = {
        "page_title": title_about_us + title_for_basic_template(),
        "development_team": DevelopmentTeam.objects.all(),
    }
    return render(request, 'about_us.html',
                  {**context, **data_for_basic_template(request)})


def faq(request):
    """
    Displays a page with useful information and processes the form
    for the user to submit a question.

    :return: Redirect to the FAQ page if the question was successfully submitted.
    Otherwise, display the FAQ page with the form.
    """
    title_faq = 'Полезная информация - '
    if request.method == 'POST':
        form = ShopFaqForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            try:
                form_for_user = form.save(commit=False)
                form_for_user.user = request.user
                form_for_user.save()
                return HttpResponseRedirect(reverse('faq'))
            except:
                form.add_error(None, 'Ошибка отправки данных!')
    else:
        form = ShopFaqForm()

    context = {
        'form': form,
        'faq': FAQ.objects.all(),
        'page_title': title_faq + title_for_basic_template(),
    }
    return render(request, 'faq.html',
                  {**context, **data_for_basic_template(request)})


def product(request, software_id):
    title_product = 'Описание програмного обеспечения - '
    software = \
        Software.objects.get(id=software_id)
    software_description = \
        FeaturesSoftware.objects.get(id=software_id)
    category = \
        SoftwareCategory.objects.get(id=software.category_id)

    context = {
        'page_title': title_product + title_for_basic_template(),
        'software_id': software_id,
        'software_name': software.name,
        'software_image': software.image.url,
        'software_price': software.price,
        'software_quantity':software.quantity,
        'software_category_id':
            software.category_id,
        'software_category_name':
            category.name,
        'software_description':
            software_description.description,
        'software_description_min_ram_mb':
            software_description.min_ram_mb,
        'software_description_video_card':
            software_description.video_card,
        'software_description_hard_disk_mb':
            software_description.hard_disk_mb,
        'software_description_operating_system':
            software_description.operating_system,
    }
    return render(request, 'product.html',
                  {**context, **data_for_basic_template(request)})


def products_catalog(request, category_id=None,
                     page_number: int = 1):
    title_product_catalog = \
        'Каталог программного обеспечения - '

    start_number: int = 1
    stop_number: int = \
        NUMBER_ITEM_PER_CATALOG_PAGE

    if page_number != 1:
        start_number = \
            NUMBER_ITEM_PER_CATALOG_PAGE + 1
        stop_number = \
            NUMBER_ITEM_PER_CATALOG_PAGE * page_number

    if category_id:
        software = \
            Software.objects.filter(category_id=
                                    category_id)
    else:
        software = Software.objects.all()

    count_all_software: int = software.count()

    if count_all_software < stop_number:
        stop_number = count_all_software

    paginator = Paginator(object_list=software.order_by('id'),
                          per_page=NUMBER_ITEM_PER_CATALOG_PAGE)
    software_paginator = paginator.page(page_number)

    context = {
        "page_title": title_product_catalog + title_for_basic_template(),
        "categories": SoftwareCategory.objects.all(),
        "software": software_paginator,
        "count_all_software": count_all_software,
        "start_number": start_number,
        "stop_number": stop_number,
    }
    return render(request, 'catalog.html',
                  {**context, **data_for_basic_template(request)})


def search_product(request):
    title_search_product = \
        'Результаты поиска - '

    q = request.GET.get('q')
    if q:
        vector = SearchVector('name')
        query = SearchQuery(q)

        software = \
            Software.objects.annotate(search=vector).filter(search=query)
    else:
        software = \
            Software.objects.all()

    start_number: int = 0
    software_count: int = \
        software.count()

    if software_count != 0:
        start_number: int = \
            software_count - (software_count - 1)

    context = {
        "software": software,
        "start_number": start_number,
        "stop_number": software_count,
        "count_all_software": software_count,
        "page_title": title_search_product + title_for_basic_template(),
    }
    return render(request, 'catalog.html',
                  {**context, **data_for_basic_template(request)})


@login_required
def cart(request):
    title_cart = \
        'Большая корзина (для сравнения товаров) - '

    cart_user_small = \
        Cart.objects.filter(user=request.user)

    cart_user_big: list = []

    for one_purchase in \
            cart_user_small.order_by('id'):

        features_software = \
            FeaturesSoftware.objects.filter(id=one_purchase.software.id).first()

        new_line = {
                    'image': one_purchase.software.image,
                    'name': one_purchase.software.name,
                    'software_id': one_purchase.software.id,
                    'one_purchase_id': one_purchase.id,
                    'description': features_software.description,
                    'operating_system': features_software.operating_system,
                    'video_card': features_software.video_card,
                    'hard_disk_mb': features_software.hard_disk_mb,
                    'min_ram_mb': features_software.min_ram_mb,
                    'quantity_in_card': one_purchase.quantity,
                    'software_price': one_purchase.software.price,
                    'one_purchase_sum': one_purchase.sum
        }
        cart_user_big.append(new_line)

    context = {
        'cart': cart_user_small,
        'big_cart': cart_user_big,
        'big_cart_total_sum': cart_user_small.total_sum,
        'page_title': title_cart + title_for_basic_template(),
    }
    return render(request, 'cart.html',
                  {**context, **data_for_basic_template(request)})


@login_required
def cart_add_one(request, software_id):
    user = request.user
    software = \
        Software.objects.get(id=software_id)
    carts = \
        Cart.objects.filter(user=user,
                            software=software)

    if not carts.exists():
        Cart.objects.create(user=user,
                            software=software,
                            quantity=1)
    else:
        cart = carts.last()
        if software.quantity > cart.quantity:
            cart.quantity += 1
            cart.save()
        else:
            message_error_for_user = \
                'Больше данного тавара нет ' \
                'на складе.'
            error(request, message_error_for_user)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def cart_delete_one(request, software_id):
    user = request.user
    software = Software.objects.get(id=software_id)
    carts = Cart.objects.filter(user=user, software=software)

    if carts.exists():
        cart = carts.last()

        if cart.quantity > 1:
            cart.quantity -= 1
            cart.save()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def cart_remove(request, cart_id):
    if Cart.objects.filter(id=cart_id).exists():
        Cart.objects.get(id=cart_id).delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

shop/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>

<!-- Basic page needs
============================================ -->
<title>{{ page_title }}</title>
<meta charset="utf-8">

<!-- Mobile specific metas
============================================ -->
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

<!-- Favicon
============================================ -->
<link rel="shortcut icon" href="{% static 'ico/favicon.png' %}">

<!-- Libs CSS
============================================ -->
{% block libs_css %} {% endblock %}

<!-- Theme CSS
============================================ -->
{% block theme_css %} {% endblock %}

</head>

{% block stile_body_two_line %} {% endblock %}

<!-- Header Container  -->
        <header id="header" class=" variantleft type_1">
            <!-- Header Top -->
			<div class="header-top">
				<div class="container">
					<div class="row">
						<div class="header-top-right collapsed-block text-right  col-sm-6 col-xs-6 compact-hidden">
							<div class="tabBlock1" id="TabBlock-1">
								<ul class="top-link list-inline">
                                    {% if user.is_authenticated %}
                                        <li class="account"><a href="{% url 'users:my_account' %}" class="top-link-checkout" title="Личный кабиинет"><span>Личный кабинет</span></a></li>
                                        <li class="signin"><a href="{% url 'users:exit_my_account' %}" class="top-link-checkout" title="Выйти"><span>Выйти</span></a></li>
                                    {% else %}
                                        <li class="signin"><a href="{% url 'users:login_user' %}" class="top-link-checkout" title="Войти"><span>Войти</span></a></li>
                                        <li class="register"><a href="{% url 'users:register' %}" title="Регистрация"><span> Регистрация </span></a></li>
                                    {% endif %}
                                    {% if user.is_superuser %}
                                        <li class="signin"><a href="{% url 'admin:index' %}" class="top-link-checkout" title="Панель-администратора"><span>Войти в панель-администратора</span></a></li>
                                    {% endif %}
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- //Header Top -->
			<!-- Header center -->
			<div class="header-center left">
				<div class="container">
					<div class="row">
						<!-- Logo -->
						<div class="navbar-logo col-md-3 col-sm-12 col-xs-7">
							<a href="{% url 'index' %}"><img src="{% static 'img/logotip.jpg' %}" title="Логотип магазина" alt="Логотип магазина"></a>
						</div>
						<!-- //Logo -->
						<!-- Search -->
						<div id="sosearchpro" class="col-xs-12 col-sm-8 col-md-5 search-pro">
							<form method="GET" action="{% url 'search' %}">
								<div id="search0" class="search input-group">
									<input class="autosearch-input form-control" type="text" value="" size="60" autocomplete="off" placeholder="Поиск программного обеспечения ... " name="q">
									<span class="input-group-btn">
										<button type="submit" class="button-search btn btn-primary"><i class="fa fa-search"></i></button>
									</span>
								</div>
							</form>
						</div>
						<!-- //Search -->
						<!-- Secondary menu -->
						<div class="col-md-4 col-sm-4 col-xs-5 shopping_cart pull-right">
                            <!--cart-->
                            {% include 'mobile_cart.html' %}
						    <!--//cart-->
						</div>
					</div>
				</div>
			</div>
            <!-- //Header center -->
			<!-- Header Bottom -->
			<div class="header-bottom">
				<div class="container">
					<div class="row">
						<!-- Main menu -->
						<div class="megamenu-hori header-bottom-right  col-md-12 col-sm-12 col-xs-12 ">
							<div class="responsive so-megamenu ">
								<nav class="navbar-default">
									<div class=" container-megamenu  horizontal">
										<div class="megamenu-wrapper">
											<div class="megamenu-pattern">
												<div class="container">
													<ul class="megamenu">
                                                        <li class="home hover">
															<p class="close-menu"></p>
															<a href="{% url 'index' %}" class="menu1">Главная</a>
														</li>
														<li class="with-sub-menu hover">
															<p class="close-menu"></p>
															<a href="{% url 'products_catalog:index' %}" class="clearfix menu1">
																<strong>Каталог</strong>
																<span class="label"></span>
															</a>
															<div class="sub-menu" style="left: 0px;">
																<div class="content">
																	<div class="row">
                                                                        {% for one_software_category in software_category %}
                                                                            <div class="col-md-4 image">
                                                                                <a href="{% url 'products_catalog:category' one_software_category.id %}"><img src="{{ one_software_category.image.url }}"></a>
                                                                                <div class="center title-submenu"></div>
                                                                                <a href="{% url 'products_catalog:category' one_software_category.id%}"> <div class="text-center"> <h3> <strong> {{ one_software_category.name }} </strong> </h3> </div> </a>
                                                                            </div>
                                                                        {% endfor %}
																	</div>
																</div>
															</div>
														</li>
													</ul>
												</div>
											</div>
										</div>
									</div>
								</nav>
							</div>
						</div>
                        <!-- //Main menu -->
                    </div>
				</div>
			</div>
		</header>
<!-- //Header Container  -->

<!-- Block Spotlight1  -->
{% block spotlight1 %} {% endblock %}
<!-- //Block Spotlight1  -->

<!-- Main Container  -->
{% block main_container %} {% endblock %}
<!-- //Main Container -->

<!-- Block Spotlight3  -->
{% block spotlight3 %} {% endblock %}
<!-- //Block Spotlight3  -->

<!-- Footer Container -->
<footer class="footer-container type_footer1">
    <!-- Footer Top Container -->
	<section class="footer-top">
		<div class="container content">
                <div class="box-information">
					<div class="module clearfix">
						<h3 class="modtitle">Наши контакты</h3>
						<div class="modcontent">
							<ul class="menu">
                                <li><a href="{% url 'about_us' %}">О нас / Наши контакты</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class=" box-information">
					<div class="module clearfix">
						<h3 class="modtitle">Информация</h3>
						<div class="modcontent">
							<ul class="menu">
								<li><a href="{% url 'faq' %}">Полезная информация</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="box-information">
					<div class="module clearfix">
						<h3 class="modtitle">Дополнительно</h3>
						<div class="modcontent">
							<ul class="menu">
								<li><a href="{% url 'sitemap' %}">Карта сайта</a></li>
							</ul>
						</div>
					</div>
				</div>
            <!-- //Block Spotlight3  -->
                <div>
                    <style> .indented {
                    padding-top: 100px;
                    padding-bottom: 100px;
                    } </style>
                <div class="indented">
                    <br>
                </div>
                </div>
                </div>
        </section>
    </footer>
<!-- //Footer Container -->

<!-- Include Libs & Plugins
============================================ -->
{% block libs_and_plugins %} {% endblock %}

<!-- Theme file
============================================ -->
{% block theme_files %} {% endblock %}
</body>
</html>

shop/templates/mobile_cart.html
{% if cart %}
<div class=" btn-group btn-shopping-cart">
    <a data-loading-text="Loading..." class="top_cart dropdown-toggle" data-toggle="dropdown">
        <div class="shopcart">
            <span class="handle pull-left"></span>
            <span class="number-shopping-cart"> {{ cart.total_quantity }} </span>
            <span class="title">Корзина покупок</span>
            <p class="text-shopping-cart cart-total-full"> {{ cart.total_sum }} ₽</p>
        </div>
    </a>
    <ul class="tab-content content dropdown-menu pull-right shoppingcart-box" role="menu">
        <li>
            <table class="table table-striped">
                <tbody>
                    {% for one_purchase in cart %}
                    <tr>
                        <td class="text-center">
                            <a href="{% url 'product:index' one_purchase.software.id %}"> <img src="{{ one_purchase.software.image.url }}" style="width:70px"> </a>
                        </td>
                        <td class="text-center">
                            <a href="{% url 'product:index' one_purchase.software.id %}"> {{ one_purchase.software.name }} </a>
                        </td>
                        <td class="text-center">
                            {{ one_purchase.quantity }}
                        </td>
                        <td class="text-center">{{ one_purchase.sum }} ₽</td>
                        <td class="text-center">
                            <a class="fa fa-times fa-minus" href="{% url 'products_catalog:cart_delete_one' one_purchase.software.id %}"></a>
                        </td>
                        <td class="text-center">
                            <a class="fa fa-times fa-plus" href="{% url 'products_catalog:cart_add_one' one_purchase.software.id %}"></a>
                        </td>
                        <td class="text-center">
                            <a class="fa fa-times " href="{% url 'products_catalog:cart_remove' one_purchase.id %}"></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </li>
        <li>
            <div>
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <td class="text-left"> <strong> Итого: </strong> </td>
                            <td class="text-right"> <strong> {{ cart.total_sum }} ₽ </strong> </td>
                        </tr>
                    </tbody>
                </table>
                <p class="text-right"> <a class="btn view-cart" href="{% url 'cart' %}"><i class="fa fa-shopping-cart"></i>Посмотреть покупки</a> </p>
            </div>
        </li>
    </ul>
</div>
{% else %}
<!-- Пустая корзина -->
    <div id="cart" class="btn-group btn-shopping-cart">
        <div class="row">
            <div class="shopcart center-block">
                <span class="handle pull-left"> </span>
                <p style="margin-left: -17px;"> Корзина пуста </p>
            </div>
        </div>
    </div>
{% endif %}

shop/templates/negative_search_result.html
<!-- сделано что бы показать мы так умеем -->

<style> .indented_for_negative_search_result
{
    padding-bottom: 250px;
    padding-top: 250px;
    text-align: center;
    border-radius: 5px;
}
</style>

<div class="indented_for_negative_search_result">
    <p> <h1> <strong>
    Продуктов (програмного обеспечения) с таким названием нет в нашем магазине.
    </strong> </h1> </p>
</div>

shop/templates/sitemap.html
{% extends 'base.html' %}
{% load static %}

<!-- Libs CSS
============================================ -->
{% block libs_css %}
    <link href="{% static 'css/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" >
    <link href="{% static 'css/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
{% endblock %}

<!-- Theme CSS
============================================ -->
{% block theme_css %}
    <link href="{% static 'css/footer1.css' %}" rel="stylesheet">
    <link href="{% static 'css/header1.css' %}" rel="stylesheet">
    <link href="{% static 'css/theme.css' %}" rel="stylesheet" id="color_scheme">
    <link href="{% static 'css/themecss/so_megamenu.css' %}" rel="stylesheet">
{% endblock %}

{% block stile_body_two_line %}
    <body class="res layout-subpage">
        <div id="wrapper" class="wrapper-full ">
{% endblock %}

<!-- Block Spotlight1  -->
{% block spotlight1 %}
{% endblock %}
<!-- //Block Spotlight1  -->

<!-- Main Container  -->
{% block main_container %}
            <div class="main-container container">
                <ul class="header-main ">
                    <li class="home"><a href="{% url 'index' %}">Главная</a><i class="fa fa-angle-right" aria-hidden="true"></i></li>
                </ul>
                <style> .indented_for_sitemap {
                    padding-top: 50px;
                    padding-bottom: 250px;
                }
                </style>
                <div class="row indented_for_sitemap">
                    <div id="content" class="col-sm-12">
                        <br><br><br>
                        <div class="row">
                            <div class="col-md-5 col-sm-6">
                                <ul class="simple-list arrow-list bold-list">
                                    <li> <a href="{% url 'index' %}"> Главная </a> </li>
                                    <li> <a href="{% url 'products_catalog:index' %}"> Каталог </a>
                                        <ul class="sitemap">
                                        {% for one_category in software_category %}
                                            <li><a href="{% url 'products_catalog:category' one_category.id %}"> <span> {{ one_category.name }} </span> </a> </li>
                                        {% endfor %}
                                        </ul>
                                    </li>
                                    <li> <a href="{% url 'users:my_account' %}"> Личный кабинет </a>
                                        <ul class="sitemap">
                                            <li><a href="{% url 'users:login_user' %}"> Вход </a> </li>
                                            <li><a href="{% url 'users:register' %}"> Регистрация </a> </li>
                                            <li><a href="{% url 'users:forgot_password' %}"> Забыл пароль </a> </li>
                                        </ul>
                                    </li>
                                    <li> <a href="{% url 'cart' %}"> Корзина </a> </li>
                                </ul>
                            </div>
                            <div class="col-md-4 col-sm-6">
                                <ul class="simple-list arrow-list bold-list">
                                    <li> <strong>НАШИ КОНТАКТЫ</strong>
                                        <ul class="sitemap">
                                            <li><a href="{% url 'about_us' %}">О нас / Наши контакты</a> </li>
                                        </ul>
                                    </li>
                                    <li> <strong>ИНФОРМАЦИЯ</strong>
                                        <ul class="sitemap">
                                            <li><a href="{% url 'faq' %}">Полезная информация</a> </li>
                                        </ul>
                                    </li>
                                    <li> <strong>ДОПОЛНИТЕЛЬНО</strong>
                                        <ul class="sitemap">
                                            <li><a href="{% url 'sitemap' %}">Карта сайта</a> </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
{% endblock %}
<!-- //Main Container -->

<!-- Block Spotlight3  -->
{% block spotlight3 %}
{% endblock %}
<!-- //Block Spotlight3  -->

<!-- Include Libs & Plugins
============================================ -->
{% block libs_and_plugins %}
    <script type="text/javascript" src="{% static 'js/jquery-2.2.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock %}

<!-- Theme files
============================================ -->
{% block theme_files %}
    <script type="text/javascript" src="{% static 'js/themejs/so_megamenu.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/themejs/application.js' %}"></script>
{% endblock %}